# Generated by Django 3.1.4 on 2020-12-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tool name', max_length=20)),
                ('description', models.CharField(help_text='Tool description', max_length=100)),
            ],
        ),
    ]
