# Generated by Django 3.1.4 on 2020-12-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(help_text='Tool description', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='title',
            field=models.CharField(help_text='Tool name', max_length=50),
        ),
    ]
