# Generated by Django 3.1.4 on 2020-12-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201208_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='html_file',
            field=models.CharField(default='x.html', help_text='html', max_length=50),
            preserve_default=False,
        ),
    ]
